<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-QBC6F12R" ignored="0" name="Zyto Automation Test" tests="26" failures="3" timestamp="25 Jul 2020 19:18:03 GMT" time="1594.452" errors="0">
  <testcase name="@BeforeTest setUp" time="0.0" classname="com.zyto.test.base.ZytoBaseTest">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;browser&amp;apos; is required by BeforeTest on method setUp but has not been marked @Optional or defined
in D:\New folder\ZytoTestAutomation\testng.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'browser' is required by BeforeTest on method setUp but has not been marked @Optional or defined
in D:\New folder\ZytoTestAutomation\testng.xml
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest setUp -->
  <testcase name="@AfterTest tearDown" time="0.0" classname="com.zyto.test.base.ZytoBaseTest">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="TC011_Email_Address_Validation" time="22.756" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC012_Existing_Email_Address_Validation" time="25.635" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC013_Invalid_Emails_Validation" time="86.743" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_010_Verify_First_Last_Name_fields" time="20.601" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_014_Verify_Password_field" time="25.343" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_015_Verify_Password_field" time="25.419" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_017_Verify_Miscmatch_of_Passwords" time="30.506" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_018_Verify__Phone_Number_field" time="44.968" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_019_Verify__Error_In_Phone_Number_field" time="45.139" classname="com.zyto.test.TestCases.Create_profile">
    <failure type="java.lang.AssertionError" message="[1;91mError message is   displayed for invalid phone number[0m">
      <![CDATA[java.lang.AssertionError: [1;91mError message is   displayed for invalid phone number[0m
at com.zyto.test.TestCases.Create_profile.TC_019_Verify__Error_In_Phone_Number_field(Create_profile.java:305)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TC_019_Verify__Error_In_Phone_Number_field -->
  <testcase name="TC_020_Verify__Error_In_Phone_Number_field" time="44.934" classname="com.zyto.test.TestCases.Create_profile">
    <failure type="java.lang.AssertionError" message="[1;91mError message is   displayed for invalid phone number[0m">
      <![CDATA[java.lang.AssertionError: [1;91mError message is   displayed for invalid phone number[0m
at com.zyto.test.TestCases.Create_profile.TC_020_Verify__Error_In_Phone_Number_field(Create_profile.java:342)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TC_020_Verify__Error_In_Phone_Number_field -->
  <testcase name="TC_021_Validate_Mandatory_DOB_Fields" time="46.1" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_022_Validate_Mandatory_DOB_Fields_With_Valid_Date" time="25.603" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_023_Validate_Age_in_Registration" time="45.788" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_024_Validate_Gender_As_Mandatory_Fields" time="43.887" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_025_Validate_Gender_Field" time="23.456" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_026_Validate_Address_Fields" time="33.357" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_027_Verify_Address_Fields_With_invalid_Data" time="33.67" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_028_Validate_Address_Fields_With_Empty_Data" time="38.007" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_029_Verify_Country_Field" time="43.436" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_030_Validate_State_Province_As_Mandate_Fields" time="43.386" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_031_Validate_State_Province_Fields" time="26.386" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_032_Validate_Post_Code_Field" time="30.24" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_033_Validate_Continue_Button" time="24.045" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_034_Validate_Errors_On_Clicking_Continue_button" time="25.472" classname="com.zyto.test.TestCases.Create_profile"/>
  <testcase name="TC_035_Validate_clearing_Errors" time="52.243" classname="com.zyto.test.TestCases.Create_profile">
    <failure type="org.openqa.selenium.StaleElementReferenceException" message="stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.116)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &amp;apos;3.14.0&amp;apos;, revision: &amp;apos;aacccce0&amp;apos;, time: &amp;apos;2018-08-02T20:19:58.91Z&amp;apos;
System info: host: &amp;apos;LAPTOP-QBC6F12R&amp;apos;, ip: &amp;apos;192.168.1.102&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_172&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.116, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\Naresh\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:58851}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: a8350db7f8fe4a5738a89e9592b2fce9">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.116)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'LAPTOP-QBC6F12R', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.116, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\Naresh\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:58851}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: a8350db7f8fe4a5738a89e9592b2fce9
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:160)
at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:403)
at com.sun.proxy.$Proxy25.getText(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:462)
at com.zyto.test.TestCases.Create_profile.TC_035_Validate_clearing_Errors(Create_profile.java:867)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC_035_Validate_clearing_Errors -->
  <testcase name="Tc_016_Verify_Password_fields_match" time="30.585" classname="com.zyto.test.TestCases.Create_profile"/>
</testsuite> <!-- Zyto Automation Test -->
